version: '3'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5

  airflow-init:
    build: .
    # image: apache/airflow:2.9.0
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__WEBSERVER__SECRET_KEY: "EaG5TcQDIFVokleKvWmeCXEFXIO8ScdSvWLRYY1om0g"
    volumes:
      - ./dags:/opt/airflow/dags
      # - ./dags:/opt/airflow/dags
      # - ./scripts:/opt/airflow/dags/repo/scripts
      - ./data:/opt/airflow/dags/repo/data
      - ./requirements.txt:/opt/airflow/dags/repo/requirements.txt
      - ./tmp:/opt/airflow/tmp
    entrypoint: /bin/bash
    command: -c "airflow db init && airflow users create --username admin --password admin --firstname airflow --lastname admin --role Admin --email admin@example.com"
    restart: on-failure


  webserver:
    build: .
    # image: apache/airflow:2.9.0
    depends_on:
      - postgres
      - airflow-init
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__WEBSERVER__SECRET_KEY: "EaG5TcQDIFVokleKvWmeCXEFXIO8ScdSvWLRYY1om0g"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/dags/repo/data
      - ./requirements.txt:/opt/airflow/dags/repo/requirements.txt
      - ./tmp:/opt/airflow/tmp
    command: webserver

  scheduler:
    build: .
    # image: apache/airflow:2.9.0
    depends_on:
      - webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "EaG5TcQDIFVokleKvWmeCXEFXIO8ScdSvWLRYY1om0g"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/dags/repo/data
      - ./requirements.txt:/opt/airflow/dags/repo/requirements.txt
      - ./tmp:/opt/airflow/tmp
    command: scheduler

volumes:
  postgres-db-volume:
